print to stderr

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -42,8 +42,8 @@ set -e
       echo "Installing Ruby gem: $gem"
 
       if ! gem install $gem &> /dev/null; then
-        echo "Failed.  Try running with sudo, or debug with \`gem install $gem\`."
-        echo "Skipping gem installation."
+        echo "Failed.  Try running with sudo, or debug with \`gem install $gem\`." >&2
+        echo "Skipping gem installation." >&2
         
         break
       fi
